# 后端 Flask/Gunicorn 服务的上游定义
upstream backend_api {
    # 使用服务名 'web'，端口是 Gunicorn 监听的 5000
    server web:5000;
}

# 前端和 API 服务的总入口
server {
    listen 80;
    server_name 8.138.234.158; # 修改为你的域名或IP
    client_max_body_size 1024M;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s; 
    # 前端静态文件的根目录 (路径是容器内的路径)
    root /var/www/frontend;
    index index.html;

    # 1. API 接口的反向代理
    # 所有以 /api/ 开头的请求都转发给后端
    location /api/ {
        proxy_pass http://backend_api; # 指向上游
        
        # 确保后端能获取到真实的请求头信息
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. 前端应用的托管
    # 对于所有其他请求，都认为是前端的请求
    location / {
        # 尝试直接提供文件，如果找不到，则返回 index.html
        # 这对于 Vue/React 等单页面应用(SPA)的路由至关重要
        try_files $uri $uri/ /index.html;
    }
}
