

services:
  # 1. Flask + Gunicorn 服务
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pshims_web
    restart: always
    env_file: ./backend/.env
    volumes:
      # 核心！将本地 backend 文件夹挂载到容器的 /app/backend 目录
      # 你在本地修改代码，容器内会立刻同步
      - ./backend:/app/backend
    command: >
      gunicorn --workers 4 --bind 0.0.0.0:5000 --reload  --access-logfile -  --error-logfile -   "backend:create_app('dev')"
    depends_on:
      - mysql
      - redis

  # 2. Nginx 服务
  nginx:
    build: 
     context: .
     dockerfile: ./nginx/Dockerfile
    container_name: pshims_nginx
    restart: always
    ports:
      # 将主机的 80 端口映射到 Nginx 容器的 80 端口，这是整个应用的入口
      - "80:80"
    depends_on:
      - web

  # 3. MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: pshims_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pshims
      MYSQL_USER: pshims_user
      MYSQL_PASSWORD: 1234
    ports:
      # 映射端口，方便使用 Navicat 等工具直连数据库调试
      - "3306:3306"
    volumes:
      # 数据库数据持久化
      - mysql_data:/var/lib/mysql
      # 挂载初始化脚本
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # 4. Redis 服务
  redis:
    image: redis:latest
    container_name: pshims_redis
    restart: always
    ports:
      # 映射端口，方便调试
      - "6379:6379"

# 定义数据卷
volumes:
  mysql_data:
